university_name:                    University of Washington
application_name_full:              EXP-Online
credits_required_for_full_time:     12.0
system_help_email:                  expohelp@u.washington.edu
base_url_host:                      expo.uw.edu
base_system_url:                    expo.uw.edu/expo
service_learning_risk_lifetime:     3.months
service_learning_staff_email:       serve@u.washington.edu
accountability_email:               acctblty@u.washington.edu