#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).

development:
 ABQIAAAAWUlJZBZE0tPv6QvuJcV46BTJQa0g3IQ9GZqIMmInSLzwtGDKaBTG2rkW_ZSlbWu6tybudRz956Bo7g

test:
 ABQIAAAAWUlJZBZE0tPv6QvuJcV46BTJQa0g3IQ9GZqIMmInSLzwtGDKaBTG2rkW_ZSlbWu6tybudRz956Bo7g

production:
 ABQIAAAAWUlJZBZE0tPv6QvuJcV46BSvPLFLHvx4J_Ol6djn51zP-sIGFBSC2d6By5Pep92kE-d3_pyk-KDyuA
